spring.application.name=wonx

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# SQL 초기화 파일(data.sql) 실행 허용
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
# 이제 진짜 tmdb api를 가져올 때 발급받은 key 대입
tmdb.api-key=REAL_API_KEY
spring.datasource.sql-script-encoding=UTF-8